import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateRepositoryReport(data) {
  const {
    repoUrl,
    stats,
    contributors,
    fileAnalysis,
    languageAnalysis,
    hotspots,
    architecture,
    recentCommits,
  } = data;

  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  // ==========================
  // Header
  // ==========================

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 32, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("Repository Analysis Report", 14, 18);

  doc.setFontSize(10);
  doc.text(
    "Generated by Code Evolution Visualizer",
    14,
    26
  );

  doc.setTextColor(0, 0, 0);

  // ==========================
  // Repository Information
  // ==========================

  doc.setFontSize(18);
  doc.text("Repository Information", 14, 45);

  autoTable(doc, {
    startY: 50,
    head: [["Field", "Value"]],
    body: [
      ["Repository URL", repoUrl || "-"],
      [
        "Generated",
        new Date().toLocaleString(),
      ],
      [
        "Total Commits",
        stats?.totalCommits || 0,
      ],
      [
        "Contributors",
        Object.keys(contributors || {}).length,
      ],
      [
        "Files",
        fileAnalysis?.totalFiles || 0,
      ],
      [
        "Hotspots",
        hotspots?.length || 0,
      ],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  // ==========================
  // Repository Statistics
  // ==========================

  doc.setFontSize(18);

  doc.text(
    "Repository Statistics",
    14,
    doc.lastAutoTable.finalY + 15
  );

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [["Metric", "Value"]],
    body: [
      [
        "Total Commits",
        stats?.totalCommits || 0,
      ],
      [
        "Contributors",
        Object.keys(contributors || {}).length,
      ],
      [
        "Files",
        fileAnalysis?.totalFiles || 0,
      ],
      [
        "Languages",
        languageAnalysis?.languages?.length || 0,
      ],
      [
        "Hotspots",
        hotspots?.length || 0,
      ],
    ],
    headStyles: {
      fillColor: [22, 163, 74],
    },
  });

  doc.save("Repository-Analysis-Report.pdf");
}